"""All tunable assumptions for the play-down / advantage / damage models live here.
Units: CE = 'card equivalent' (the value of drawing one random card from your deck).
"""
# Probability the game is still running at the start of your own turn t (t = 1..10).
P_ALIVE = [1.0, 1.0, 1.0, 1.0, 0.92, 0.78, 0.60, 0.40, 0.22, 0.10]
PRIZE_TO_CE = 3.0          # 1 Prize card of progress ~ 3 CE
HP_PER_PRIZE = 140.0       # meta-weighted HP you must chew through per Prize (recomputed from data when possible)
CE = {
    "draw": 1.0,           # draw 1 random card
    "tutor": 1.5,          # search 1 specific card
    "select2": 1.25,       # look at 2, keep 1
    "accel": 1.0,          # one extra Energy attachment action (tempo)
    "energy_card": 1.0,    # an Energy card that didn't come from your hand
    "retreat_energy": 2.0, # each Energy you didn't have to discard to retreat (card + attachment)
    "discard_cost": 0.5,   # each card you must discard as a cost
    "hand_reset": 0.6,     # each card shuffled away by your own shuffle-draw
    "opp_card": 0.7,       # each card removed/disrupted from the opponent's hand
}
def dmg_ce(hp):
    """Convert damage (HP) into CE through Prize progress."""
    return hp / HP_PER_PRIZE * PRIZE_TO_CE

# ---------------- support Pokémon play-down model ----------------
# horizon: own turn by which the card 'should' hit the bench if wanted.
# desire: P(choose to play | accessible) before matchup modifiers. 'mods' are applied per opponent archetype
# using opponent features (see models.py: items, dragon, cursed_blast, munkidori, bench_snipe, stadiums, ex_attackers).
SUPPORT = {
    "Budew":                {"horizon": {"first": 2, "second": 1}, "desire": 0.92, "mods": {"items_low": 0.6},
                             "by_arch": {"n-zoroark": 0.75, "slowking-scr": 0.6, "lopunny-dusknoir": 0.75}},
    "Latias ex":            {"horizon": 2, "desire": 0.70, "by_arch": {"basic-box-m": 0.95, "slowking-scr": 0.90, "raging-bolt-ogerpon": 0.95,
                                                                        "mew-ex-30c": 0.90, "lopunny-dusknoir": 0.80, "dhelmise-pbl": 0.75}},
    "Fezandipiti ex":       {"horizon": 5, "desire": 0.80},
    "Meowth ex":            {"horizon": 2, "desire": 0.75, "by_arch": {"basic-box-m": 0.85, "ogerpon-meganium-hydrapple": 0.85}},
    "Munkidori":            {"horizon": 3, "desire": 0.90},
    "Shaymin":              {"horizon": 3, "desire": 0.55, "mods": {"bench_snipe": 1.5}},
    "Lillie's Clefairy ex": {"horizon": 3, "desire": 0.35, "mods": {"dragon": 2.7}},
    "Psyduck":              {"horizon": 3, "desire": 0.15, "mods": {"cursed_blast": 6.0}},
    "Dudunsparce":          {"horizon": 3, "desire": 0.80},
    "Dunsparce":            {"horizon": 2, "desire": 0.80},
    "Pecharunt ex":         {"horizon": 2, "desire": 0.80},
    "Chien-Pao":            {"horizon": 3, "desire": 0.35, "mods": {"stadiums": 2.0}},
    "Genesect":             {"horizon": 2, "desire": 0.60},
    "Tatsugiri":            {"horizon": 1, "desire": 0.55},
    "Patrat":               {"horizon": 3, "desire": 0.15, "mods": {"munkidori": 6.0}},
    "Mew ex":               {"horizon": 3, "desire": 0.60},
    "Moltres":              {"horizon": 4, "desire": 0.40, "mods": {"ex_attackers": 1.4}, "by_arch": {"lopunny-dudunsparce": 0.6}},
    "Fan Rotom":            {"horizon": 1, "desire": 0.85},
    "Iron Leaves ex":       {"horizon": 4, "desire": 0.55},
    "Teal Mask Ogerpon ex": {"horizon": 2, "desire": 0.95},
    "Kyurem":               {"horizon": 5, "desire": 0.35},
    "Rabsca":               {"horizon": 3, "desire": 0.35, "mods": {"bench_snipe": 1.6}},
    "Genesect ex":          {"horizon": 2, "desire": 0.85},
    "Lunatone":             {"horizon": 2, "desire": 0.95},
}
SPREAD_OR_SNIPE = {"Dragapult ex", "Munkidori", "Dusknoir", "Dusclops", "Iron Crown ex", "Wellspring Mask Ogerpon ex",
                   "Kyurem", "Fezandipiti ex", "Annihilape", "Froslass", "Mega Skarmory ex", "Sinistcha"}
CURSED_BLAST = {"Dusknoir", "Dusclops"}
COUNTER_MOVERS = {"Munkidori"}

# ---------------- Budew / item lock ----------------
ITEM_LOCK = {
    # name: how the lock is applied
    "Budew": "attack:0",            # Itchy Pollen, free attack
    "Frillish": "attack:1",
    "Flaaffy": "attack:2",
    "Galvantula ex": "attack:3",
    "Tyranitar": "ability:active",
    "Jellicent ex": "ability:active",
}
BUDEW_LOCK_TURNS = {"first": 1.5, "second": 1.9}   # expected Itchy Pollen uses per game once Budew is out
ITEM_LOCK_CE_PER_ITEM = 0.5                        # value of each opposing Item held back for a turn
ITEM_LOCK_SETUP_PENALTY = 1.0                      # extra tempo lost by setup decks (Rare Candy / Poffin turns)

# ---------------- engines (per-turn / on-play abilities) ----------------
# kind: turn (once per turn per copy), turn1 (once per turn total), play (once when played/evolved), passive (per turn),
#       attack (uses an attack), first (first turn only)
# value: dict of CE components per use; 'dmg' / 'heal' in HP get converted with dmg_ce.
ENGINES = {
    "Teal Mask Ogerpon ex": {"kind": "turn", "cap": 3, "trigger": "grass_in_hand", "value": {"accel": 1, "draw": 1}, "surv": 0.97, "max_uses": 9},
    "Drakloak":             {"kind": "turn", "cap": 2, "trigger": 0.95, "value": {"select2": 1}, "surv": 0.90, "decay": 0.12},
    "Dudunsparce":          {"kind": "play", "cap": 3, "trigger": 0.9, "value": {"draw": 3}},
    "Fezandipiti ex":       {"kind": "turn1", "cap": 1, "trigger": "ko_last_turn", "value": {"draw": 3}, "surv": 0.95},
    "Meowth ex":            {"kind": "play", "cap": 2, "trigger": 0.85, "value": {"tutor": 1}},
    "Kadabra":              {"kind": "play", "cap": 4, "trigger": 0.9, "value": {"draw": 2}},
    "Alakazam":             {"kind": "play", "cap": 3, "trigger": 0.9, "value": {"draw": 3}},
    "N's Zoroark ex":       {"kind": "turn", "cap": 2, "trigger": 0.9, "value": {"draw": 2, "discard": 1}, "surv": 0.92},
    "Mega Kangaskhan ex":   {"kind": "turn1", "cap": 1, "trigger": 0.7, "value": {"draw": 2}, "surv": 0.93},
    "Lunatone":             {"kind": "turn1", "cap": 1, "trigger": 0.75, "value": {"draw": 3, "discard": 1}, "surv": 0.92},
    "Blaziken ex":          {"kind": "turn", "cap": 1, "trigger": 0.85, "value": {"accel": 1, "energy_card": 1}, "surv": 0.92},
    "Metang":               {"kind": "turn", "cap": 3, "trigger": "metal_top4", "value": {"accel": 1, "energy_card": 1}, "surv": 0.88, "decay": 0.1, "max_uses": 7},
    "Hydrapple ex":         {"kind": "turn", "cap": 1, "trigger": "grass_in_hand", "value": {"accel": 1, "heal": 30}, "surv": 0.92},
    "Meganium":             {"kind": "passive", "cap": 1, "trigger": 0.9, "value": {"accel": 1}, "surv": 0.9},
    "Thwackey":             {"kind": "turn", "cap": 2, "trigger": 0.8, "value": {"tutor": 1}, "surv": 0.88},
    "Genesect ex":          {"kind": "turn", "cap": 1, "trigger": 0.45, "value": {"tutor": 2}, "surv": 0.93},
    "Latias ex":            {"kind": "passive", "cap": 1, "trigger": 0.6, "value": {"retreat_energy": 1.3}, "surv": 0.95},
    "Budew":                {"kind": "attack", "cap": 1, "trigger": 1.0, "value": {"item_lock": 1}, "surv": 0.85},
    "Munkidori":            {"kind": "turn", "cap": 2, "trigger": 0.8, "value": {"dmg": 30, "heal": 30}, "surv": 0.9},
    "Dusclops":             {"kind": "play", "cap": 2, "trigger": 0.75, "value": {"dmg": 50, "prize_given": 1}},
    "Dusknoir":             {"kind": "play", "cap": 2, "trigger": 0.75, "value": {"dmg": 130, "prize_given": 1}},
    "Iron Leaves ex":       {"kind": "play", "cap": 1, "trigger": 0.6, "value": {"retreat_energy": 1, "accel": 2}},
    "Pecharunt ex":         {"kind": "turn1", "cap": 1, "trigger": 0.6, "value": {"retreat_energy": 1, "dmg": -10}, "surv": 0.93},
    "Tatsugiri":            {"kind": "turn", "cap": 1, "trigger": 0.35, "value": {"tutor": 0.75}, "surv": 0.9},
    "Fan Rotom":            {"kind": "first", "cap": 1, "trigger": 0.9, "value": {"tutor": 2.5}},
    "Hariyama":             {"kind": "play", "cap": 2, "trigger": 0.8, "value": {"gust": 1}},
    "Noctowl":              {"kind": "play", "cap": 2, "trigger": 0.8, "value": {"tutor": 2}},
    "Shaymin":              {"kind": "passive", "cap": 1, "trigger": 0.25, "value": {"heal": 100}, "surv": 0.92},
    "Lillie's Clefairy ex": {"kind": "passive", "cap": 1, "trigger": "dragon_opp", "value": {"dmg": 100}, "surv": 0.92},
    "Psyduck":              {"kind": "passive", "cap": 1, "trigger": "cursed_blast_opp", "value": {"heal": 90}, "surv": 0.9},
    "Chien-Pao":            {"kind": "play", "cap": 1, "trigger": 0.6, "value": {"opp_card": 1.5}},
    "Genesect":             {"kind": "passive", "cap": 1, "trigger": 0.15, "value": {"opp_card": 1.5}, "surv": 0.9},
    "Dunsparce":            {"kind": "attack", "cap": 1, "trigger": 0.4, "value": {"retreat_energy": 1}, "surv": 0.9},
    "Froslass":             {"kind": "passive", "cap": 2, "trigger": 1.0, "value": {"dmg": 25}, "surv": 0.88},
    "Toxtricity":           {"kind": "turn", "cap": 2, "trigger": 0.7, "value": {"accel": 1, "energy_card": 1, "dmg": -20}, "surv": 0.9},
    "Iron Crown ex":        {"kind": "passive", "cap": 1, "trigger": 0.6, "value": {"dmg": 20}, "surv": 0.93},
    "Patrat":               {"kind": "passive", "cap": 1, "trigger": "munkidori_opp", "value": {"heal": 30}, "surv": 0.85},
    "Rabsca":               {"kind": "passive", "cap": 1, "trigger": 0.3, "value": {"heal": 60}, "surv": 0.85},
    "Annihilape":           {"kind": "passive", "cap": 1, "trigger": 0.25, "value": {"heal": 75}, "surv": 0.9},
    "Cynthia's Gabite":     {"kind": "turn", "cap": 2, "trigger": 0.6, "value": {"tutor": 1}, "surv": 0.88},
    "Cynthia's Roserade":   {"kind": "passive", "cap": 1, "trigger": 0.8, "value": {"dmg": 30}, "surv": 0.88},
    "Toucannon":            {"kind": "turn", "cap": 2, "trigger": 0.95, "value": {"draw": 1}, "surv": 0.9},
    "Marnie's Grimmsnarl ex": {"kind": "play", "cap": 2, "trigger": 0.9, "value": {"accel": 3, "energy_card": 3}},
    "Team Rocket's Spidops": {"kind": "turn", "cap": 3, "trigger": 0.7, "value": {"accel": 1, "energy_card": 1}, "surv": 0.9, "max_uses": 6},
    "Mega Greninja ex":     {"kind": "turn1", "cap": 1, "trigger": 0.6, "value": {"dmg": 60, "discard": 1}, "surv": 0.9},
    "Ethan's Quilava":      {"kind": "turn", "cap": 2, "trigger": 0.6, "value": {"tutor": 1}, "surv": 0.88},
    "Hop's Snorlax":        {"kind": "passive", "cap": 1, "trigger": 0.8, "value": {"dmg": 30}, "surv": 0.9},
    "Dipplin":              {"kind": "passive", "cap": 1, "trigger": 0.6, "value": {"dmg": 100}, "surv": 0.85},
    "Seaking":              {"kind": "passive", "cap": 1, "trigger": 0.6, "value": {"dmg": 60, "draw": 2}, "surv": 0.85},
    "Flutter Mane":         {"kind": "passive", "cap": 1, "trigger": 0.3, "value": {"opp_card": 1}, "surv": 0.85},
    "Abra":                 {"kind": "turn1", "cap": 1, "trigger": 0.25, "value": {"retreat_energy": 1}, "surv": 0.8},
    "Pecharunt":            {"kind": "passive", "cap": 1, "trigger": 0.4, "value": {"dmg": 50}, "surv": 0.85},
    "Eelektrik":            {"kind": "turn", "cap": 2, "trigger": 0.8, "value": {"accel": 1, "energy_card": 1}, "surv": 0.88, "max_uses": 6},
    "Mega Venusaur ex":     {"kind": "turn1", "cap": 1, "trigger": 0.6, "value": {"accel": 1}, "surv": 0.93},
    "Steven's Metagross ex": {"kind": "turn1", "cap": 1, "trigger": 0.8, "value": {"accel": 2, "energy_card": 2}, "surv": 0.93},
    "Mega Dragonite ex":    {"kind": "turn1", "cap": 1, "trigger": 0.5, "value": {"retreat_energy": 1}, "surv": 0.93},
    "Bouffalant":           {"kind": "passive", "cap": 1, "trigger": 0.6, "value": {"heal": 60}, "surv": 0.9},
    "Crustle":              {"kind": "passive", "cap": 1, "trigger": "ex_opp", "value": {"heal": 120}, "surv": 0.92},
    "Mew ex":               {"kind": "passive", "cap": 1, "trigger": 0.3, "value": {"retreat_energy": 0.5, "tutor": 0.5}, "surv": 0.9},
    "Tyranitar":            {"kind": "passive", "cap": 1, "trigger": 0.6, "value": {"item_lock": 1}, "surv": 0.9},
    "Jellicent ex":         {"kind": "passive", "cap": 1, "trigger": 0.6, "value": {"item_lock": 1}, "surv": 0.9},
}
GUST_CE = 2.0

# ---------------- trainers: CE per play (before plays-per-game) ----------------
TRAINER_CE = {
    "Lillie's Determination": (4.6, "draw 6 (8 at 6 Prizes) minus ~3 cards shuffled away"),
    "Judge": (3.0, "draw 4 minus own hand, plus opponent hand disruption"),
    "Boss's Orders": (2.0 + 0.0, "gust: chooses the KO target (~0.65 Prize of extra value)"),
    "Ultra Ball": (0.75, "tutor any Pokémon (1.75) minus 2 discards"),
    "Poké Pad": (1.5, "tutor a non-Rule Box Pokémon"),
    "Buddy-Buddy Poffin": (3.25, "two Basics straight to the Bench"),
    "Nest Ball": (1.6, "Basic straight to the Bench"),
    "Night Stretcher": (1.25, "recover a Pokémon or basic Energy"),
    "Dawn": (4.5, "Basic + Stage 1 + Stage 2 tutor"),
    "Hilda": (3.0, "Evolution Pokémon + Energy tutor"),
    "Cyrano": (3.75, "up to 3 Pokémon ex"),
    "Crispin": (3.25, "1 Energy to hand + 1 attached (acceleration)"),
    "Team Rocket's Petrel": (1.75, "tutor any Trainer"),
    "Brock's Scouting": (2.5, "2 Basics or 1 Evolution"),
    "Rosa's Encouragement": (3.0, "2 Energy from discard onto a Stage 2 (only when behind)"),
    "Gwynn": (3.5, "discard up to 2 non-Rule Box Pokémon, draw 3 each"),
    "Unfair Stamp": (5.5, "you draw 5 / opponent to 2, only after a KO"),
    "Special Red Card": (1.6, "late-game hand disruption to 3"),
    "Crushing Hammer": (1.0, "50%: remove an Energy"),
    "Enhanced Hammer": (2.0, "remove a Special Energy"),
    "Rare Candy": (2.5, "skip Stage 1: a full turn of evolution tempo"),
    "Switch": (1.5, "free pivot"),
    "Energy Switch": (1.0, "move a basic Energy"),
    "Air Balloon": (2.0, "-2 retreat, reusable"),
    "Secret Box": (4.5, "4 tutors minus 3 discards"),
    "Pokégear 3.0": (1.2, "~80% to find a Supporter in top 7"),
    "Fighting Gong": (1.5, "tutor Fighting Basic or Energy"),
    "Sacred Ash": (1.5, "5 Pokémon back to deck"),
    "Energy Recycler": (1.0, "5 basic Energy back to deck"),
    "Wondrous Patch": (2.0, "Energy from discard to a benched Psychic"),
    "N's PP Up": (2.0, "Energy from discard to a benched N's Pokémon"),
    "Glass Trumpet": (4.0, "2 Energy from discard (needs Tera)"),
    "Premium Power Pro": (0.65, "+30 damage this turn"),
    "Black Belt's Training": (0.85, "+40 vs ex this turn"),
    "Jumbo Ice Cream": (1.7, "heal 80"),
    "Hero's Cape": (2.1, "+100 HP"),
    "Bug Catching Set": (2.0, "~1.6 Grass Pokémon/Energy from top 7"),
    "Xerosic's Machinations": (2.5, "opponent discards down to 3"),
    "Eri": (1.4, "discard up to 2 opposing Items"),
    "Lana's Aid": (3.0, "recover 3"),
    "Ciphermaniac's Codebreaking": (2.5, "stack 2 chosen cards on top"),
    "Kieran": (1.5, "switch or +30 vs ex"),
    "Prime Catcher": (3.5, "gust + switch"),
    "Tool Scrapper": (1.5, "remove 2 tools"),
    "Team Rocket's Transceiver": (1.5, "tutor a TR Supporter"),
    "Wally's Compassion": (3.0, "full heal of a Mega (returns Energy to hand)"),
    "Pokémon Center Lady": (1.3, "heal 60"),
    "Brave Bangle": (0.9, "+30 vs ex, persistent"),
    "Binding Mochi": (1.2, "+40 while Poisoned"),
    "Handheld Fan": (1.0, "moves an Energy off the attacker"),
    "Lucky Helmet": (1.4, "draw 2 when hit"),
    "Maximum Belt": (1.0, "+50 vs ex"),
    "Briar": (2.0, "+1 Prize on a Tera KO at 2 Prizes left"),
    "Gladion's Final Battle": (1.7, "+80 for non-Rule Box when it's the last card"),
    "Janine's Secret Art": (3.7, "2 Darkness Energy from deck attached (Active gets Poisoned)"),
    "Team Rocket's Giovanni": (2.8, "pivot + gust for Team Rocket's decks"),
    "Team Rocket's Proton": (3.5, "3 Basic TR Pokémon, usable going first T1"),
    "Team Rocket's Ariana": (3.5, "draw to 5 (8 if all TR)"),
    "Team Rocket's Archer": (4.5, "you draw 5 / opponent 3, after a TR KO"),
    "Surfer": (2.6, "pivot + draw to 5"),
    "Ruffian": (2.2, "remove a Tool and a Special Energy"),
    "Bianca's Devotion": (2.0, "full heal of a Pokémon at 30 HP or less"),
    "Precious Trolley": (4.5, "any number of Basics to the Bench (ACE SPEC)"),
    "Miracle Headset": (3.0, "2 Supporters back (ACE SPEC)"),
    "Transformation Tome": (1.0, "pair: swap a Basic in play with one in discard"),
    "Mega Signal": (1.5, "tutor a Mega Evolution ex"),
    "Hop's Bag": (3.0, "2 Basic Hop's Pokémon to the Bench"),
    "Energy Retrieval": (2.0, "2 basic Energy back to hand"),
    "Iron Defender": (0.9, "-30 damage to Metal Pokémon for a turn"),
    "Ethan's Adventure": (3.6, "3 Ethan's Pokémon / Fire Energy"),
    "Misty's Vitality": (5.0, "up to 4 Water Energy attached, ends turn"),
    "Firebreather": (3.5, "up to 7 Fire Energy to hand"),
    "Tarragon": (3.2, "recover 4 Fighting Pokémon / Energy"),
    "Harlequin": (2.5, "coin-flip hand reset"),
    "AZ's Tranquility": (2.4, "pivot + heal 80 on an ex"),
    "Emma": (1.5, "draw per Pokémon in opponent's hand"),
    "Canari": (4.0, "4 Lightning Pokémon (discard 1)"),
    "Super Potion": (1.2, "heal 60, discard an Energy"),
    "Poké Ball": (0.8, "50%: tutor a Pokémon"),
    "Pokémon Catcher": (1.0, "50%: gust"),
    "Energy Swatter": (1.0, "an opposing Energy from hand to deck bottom"),
    "Hop's Choice Band": (1.3, "-1 cost and +30 for Hop's Pokémon"),
    "Cynthia's Power Weight": (1.4, "+70 HP on a Cynthia's Pokémon"),
    "Adversity Policy": (0.8, "draw 3 when hit by your Weakness type"),
    # Stadiums: value per stadium played (about 2 turns in play)
    "Risky Ruins": (1.8, "2 damage counters on most opposing Basics benched"),
    "Team Rocket's Watchtower": (1.5, "turns off Colorless Abilities (Meowth ex, Dudunsparce, Kangaskhan...)"),
    "Jamming Tower": (1.0, "turns off all Tools"),
    "Battle Cage": (1.5, "blocks bench counters (Phantom Dive, Munkidori)"),
    "Area Zero Underdepths": (1.5, "8 Bench spots with a Tera in play"),
    "Gravity Mountain": (1.3, "-30 HP on Stage 2s"),
    "Team Rocket's Factory": (3.0, "draw 2 per TR Supporter"),
    "Prism Tower": (0.6, "discard 2, draw 1 each turn"),
    "Festival Grounds": (1.0, "enables Festival Lead double attacks"),
    "Forest of Vitality": (2.0, "Grass evolutions the turn they're played"),
    "Academy at Night": (0.8, "put a card on top each turn"),
    "N's Castle": (2.0, "N's Pokémon retreat for free"),
    "Lumiose City": (0.8, "Basic to Bench, ends your turn"),
    "Nighttime Mine": (1.0, "Tera attacks cost 1 more"),
}

# ---------------- attackers: typical damage per attack ----------------
# dmg: expected damage to the Active in a typical game state; spread: extra bench damage/counters per attack;
# ignore_wr: placing counters / text that ignores Weakness; first: typical own turn of first attack (avg of going 1st/2nd);
# cadence: share of later turns this card is the attacker; note: how dmg was estimated.
ATTACKERS = {
    "Dragapult ex":            dict(type="Dragon", dmg=200, spread=60, first=2.5, cadence=0.85, note="Phantom Dive 200 + 6 counters"),
    "N's Zoroark ex":          dict(type="Darkness", dmg=210, first=2.5, cadence=0.8, note="Night Joker copying Zekrom 250 / Reshiram 170"),
    "Teal Mask Ogerpon ex":    dict(type="Grass", dmg=180, first=2.0, cadence=0.35, note="30 + 30 x ~5 Energy on both Actives"),
    "Lillie's Clefairy ex":    dict(type="Psychic", dmg=160, first=2.5, cadence=0.25, fairy_zone=True, note="20 + 20 x ~7 Benched"),
    "Mega Kangaskhan ex":      dict(type="Colorless", dmg=250, first=2.5, cadence=0.45, note="200 + 50 per heads (E=1)"),
    "Alakazam":                dict(type="Psychic", dmg=160, ignore_wr=True, first=2.5, cadence=0.8, note="2 counters x ~8 cards in hand"),
    "Slowking":                dict(type="Psychic", dmg=140, first=2.5, cadence=0.8, note="Seek Inspiration (copied attack) / Super Psy Bolt 120"),
    "Mega Excadrill ex":       dict(type="Metal", dmg=280, first=3.0, cadence=0.8, note="Maximum Drilling 200 / 330 with 2 extra Energy"),
    "Dipplin":                 dict(type="Grass", dmg=200, first=2.5, cadence=0.8, note="Do the Wave 20 x 5 Bench, twice via Festival Lead"),
    "Dhelmise":                dict(type="Psychic", dmg=170, first=3.0, cadence=0.85, note="30 + 140 once 4 Hide 'n' Sneak are discarded"),
    "Crustle":                 dict(type="Grass", dmg=120, first=2.0, cadence=0.85, note="Superb Scissors 120 (ignores effects); walls ex"),
    "Hydrapple ex":            dict(type="Grass", dmg=330, first=3.0, cadence=0.6, note="30 + 30 x Grass Energy (doubled by Meganium)"),
    "Mega Lucario ex":         dict(type="Fighting", dmg=200, first=2.5, cadence=0.75, note="Mega Brave 270 alternating with Aura Jab 130"),
    "Hariyama":                dict(type="Fighting", dmg=210, first=3.0, cadence=0.25, note="Wild Press 210 (70 to self)"),
    "Mega Lopunny ex":         dict(type="Colorless", dmg=210, first=2.5, cadence=0.8, note="Gale Thrust 230 after a switch / Spiky Hopper 160"),
    "Team Rocket's Honchkrow": dict(type="Darkness", dmg=180, first=2.5, cadence=0.8, note="60 x ~3 TR Supporters discarded"),
    "Cynthia's Garchomp ex":   dict(type="Fighting", dmg=220, first=3.0, cadence=0.8, note="Draconic Buster 260 / Corkscrew Dive 100"),
    "Mega Sharpedo ex":        dict(type="Darkness", dmg=250, first=2.5, cadence=0.8, note="Hungry Jaws 120 + 150 when damaged"),
    "Marnie's Grimmsnarl ex":  dict(type="Darkness", dmg=180, spread=30, first=3.0, cadence=0.8, note="Shadow Bullet 180 + 30 bench"),
    "Team Rocket's Mewtwo ex": dict(type="Psychic", dmg=260, first=3.0, cadence=0.7, note="160 + 60 per Energy discarded (~1.7)"),
    "Raging Bolt ex":          dict(type="Dragon", dmg=280, first=2.0, cadence=0.6, note="70 x ~4 Energy discarded"),
    "Mega Greninja ex":        dict(type="Water", dmg=200, spread=60, first=3.0, cadence=0.8, note="Ninja Spinner 120+80; Mortal Shuriken 6 counters"),
    "Ethan's Typhlosion":      dict(type="Fire", dmg=220, first=3.0, cadence=0.8, note="40 + 60 x ~3 Ethan's Adventure"),
    "Arboliva ex":             dict(type="Grass", dmg=120, ignore_wr=True, first=3.0, cadence=0.5, note="Oil Salvo 6 x 20 anywhere"),
    "Mega Venusaur ex":        dict(type="Grass", dmg=240, first=3.0, cadence=0.8, note="Jungle Dump 240 + heal 30"),
    "Mega Chandelure ex":      dict(type="Psychic", dmg=230, first=3.0, cadence=0.8, note="130 + 50 per retreat cost (+1 from Binding Flame)"),
    "Greninja ex":             dict(type="Water", dmg=170, spread=60, first=3.0, cadence=0.8, note="Shinobi Blade 170 / Mirage Barrage 2x120"),
    "Mega Starmie ex":         dict(type="Water", dmg=180, spread=25, first=2.5, cadence=0.8, note="Nebula Beam 210 / Jetting Blow 120+50"),
    "Mew ex":                  dict(type="Psychic", dmg=160, first=2.5, cadence=0.4, note="Memory Helix copying a Benched attacker"),
    "Hop's Trevenant":         dict(type="Psychic", dmg=130, first=2.5, cadence=0.8, note="Horrifying Revenge 30 + 100"),
    "Ceruledge ex":            dict(type="Fire", dmg=190, first=2.5, cadence=0.8, note="30 + 20 x ~8 Energy in discard"),
    "Beedrill ex":             dict(type="Grass", dmg=270, first=3.0, cadence=0.8, note="110 x ~2.5 Beedrill in play"),
    "Toucannon":               dict(type="Colorless", dmg=200, first=3.0, cadence=0.8, note="60 + 20 x ~7 Benched"),
    "Mega Absol ex":           dict(type="Darkness", dmg=200, first=2.5, cadence=0.6, note="Claw of Darkness 200 (+ hand discard)"),
    "Mega Manectric ex":       dict(type="Lightning", dmg=260, first=3.0, cadence=0.7, note="Riotous Blasting 200/330, Flash Ray 120"),
    "Toxtricity":              dict(type="Darkness", dmg=100, first=3.0, cadence=0.2, note="Gentle Slap 100"),
    "Moltres":                 dict(type="Fire", dmg=110, first=2.0, cadence=0.25, vs_ex_only=True, note="20 + 90 vs ex for one Energy"),
    "Iron Leaves ex":          dict(type="Grass", dmg=180, first=3.0, cadence=0.25, note="Prism Edge 180"),
    "Wellspring Mask Ogerpon ex": dict(type="Water", dmg=100, spread=120, first=3.0, cadence=0.2, note="Torrential Pump 100 + 120 bench"),
    "Fezandipiti ex":          dict(type="Darkness", dmg=0, spread=100, first=3.5, cadence=0.15, note="Cruel Arrow 100 anywhere"),
    "Dudunsparce ex":          dict(type="Colorless", dmg=150, first=3.0, cadence=0.4, note="Tenacious Tail 60 x ex / Destructive Drill 150"),
    "Metagross":               dict(type="Metal", dmg=300, first=3.5, cadence=0.6, note="Metallic Hammer 150 + 150"),
    "Kyurem":                  dict(type="Dragon", dmg=110, spread=220, first=3.5, cadence=0.3, note="Trifrost 110 to 3 Pokémon"),
    "Yveltal":                 dict(type="Darkness", dmg=110, first=3.0, cadence=0.3, note="Dark Feather 110"),
    "Bloodmoon Ursaluna ex":   dict(type="Colorless", dmg=240, first=4.0, cadence=0.5, note="Blood Moon 240"),
    "Mega Dragonite ex":       dict(type="Dragon", dmg=330, first=3.0, cadence=0.7, note="Ryuno Glide 330"),
    "Hop's Zacian ex":         dict(type="Metal", dmg=200, spread=15, first=2.5, cadence=0.7, note="Brave Slash 240 alternating with Insta-Strike"),
    "Steven's Metagross ex":   dict(type="Metal", dmg=200, first=3.0, cadence=0.8, note="Metal Stomp 200"),
    "Gengar ex":               dict(type="Darkness", dmg=130, ignore_wr=True, first=3.0, cadence=0.8, note="Chaotic Pain 13 counters anywhere"),
    "Mega Gengar ex":          dict(type="Darkness", dmg=230, first=3.0, cadence=0.8, note="Void Gale 230"),
    "Mega Froslass ex":        dict(type="Water", dmg=250, first=2.5, cadence=0.8, note="50 x ~5 cards in opponent's hand"),
    "Mega Darkrai ex":         dict(type="Darkness", dmg=220, first=2.5, cadence=0.8, note="Dusk Raid 110 + 110"),
    "Hydreigon ex":            dict(type="Darkness", dmg=200, first=3.0, cadence=0.8, note="Dark Bite 200"),
    "Mega Charizard X ex":     dict(type="Fire", dmg=270, first=3.0, cadence=0.8, note="90 x ~3 Fire discarded"),
    "Mega Camerupt ex":        dict(type="Fire", dmg=280, first=3.0, cadence=0.7, note="Volcanic Meteor 280"),
    "Team Rocket's Spidops":   dict(type="Grass", dmg=120, first=2.5, cadence=0.3, note="30 x ~4 TR Pokémon"),
    "N's Zekrom":              dict(type="Dragon", dmg=250, first=3.5, cadence=0.2, note="Rampaging Thunder 250"),
    "N's Reshiram":            dict(type="Dragon", dmg=170, first=3.5, cadence=0.2, note="Virtuous Flame 170"),
    "Munkidori":               dict(type="Psychic", dmg=60, first=2.5, cadence=0.1, note="Mind Bend 60"),
}
